#!/usr/bin/env python3
"""Generate docs/IMPLEMENTATION-STATUS.md from docs/implementation-status.yaml.

The report is the "decided vs built vs effective" line as data rather than
scattered prose (the failure mode that produced repeated handbook
overstatements). The YAML is the source of truth; this script derives the
Markdown and CI drift-checks it.

Validation (the build fails on any of these):
  - every entry's `adr` is well-formed (ADR-NNNN) and resolves to a real
    docs/decisions/NNNN-*.md;
  - `status` uses the controlled vocabulary;
  - `tracking` entries (if any) are integers;
  - every *accepted* ADR has an entry — a new decision cannot silently dodge
    the report;
  - no duplicate entries.

Status is authoritative structured data; it is never inferred from ADR prose.

Exit 0 when everything passes and the report is written; 1 with one line per
finding otherwise.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "docs" / "implementation-status.yaml"
OUT = REPO / "docs" / "IMPLEMENTATION-STATUS.md"
ADR_DIR = REPO / "docs" / "decisions"

VOCAB = ["implemented", "partial", "decided", "proposed"]
VOCAB_MEANING = {
    "implemented": "mechanisms built and exercised here",
    "partial": "some built; the rest planned",
    "decided": "accepted contract; no code here yet",
    "proposed": "open RFC, not yet accepted",
}

errors: list[str] = []


def err(message: str) -> None:
    errors.append(message)


def adr_frontmatter() -> dict[str, dict]:
    """Return {ADR-NNNN: {title, status, file}} for every docs/decisions/NNNN-*.md."""
    out: dict[str, dict] = {}
    for path in sorted(ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md")):
        text = path.read_text(encoding="utf-8")
        m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        if not m:
            err(f"{path.relative_to(REPO)}: no YAML frontmatter")
            continue
        meta = yaml.safe_load(m.group(1)) or {}
        key = f"ADR-{int(meta['id']):04d}"
        out[key] = {"title": str(meta["title"]).strip(), "status": meta["status"], "file": path.name}
    return out


def join(items: list) -> str:
    return "<br>".join(str(i) for i in items) if items else "—"


def main() -> int:
    adrs = adr_frontmatter()
    accepted = {k for k, v in adrs.items() if v["status"] == "accepted"}

    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or {}
    entries = data.get("decisions", [])

    seen: set[str] = set()
    by_status: dict[str, list[dict]] = {s: [] for s in VOCAB}

    for e in entries:
        adr = e.get("adr", "")
        if not re.fullmatch(r"ADR-\d{4}", adr):
            err(f"entry '{adr}': not a well-formed ADR id (ADR-NNNN)")
            continue
        if adr in seen:
            err(f"{adr}: duplicate entry")
            continue
        seen.add(adr)
        if adr not in adrs:
            err(f"{adr}: no docs/decisions/ file for this id")
            continue
        if e.get("status") not in VOCAB:
            err(f"{adr}: status '{e.get('status')}' not in {VOCAB}")
            continue
        for t in e.get("tracking", []) or []:
            if not isinstance(t, int):
                err(f"{adr}: tracking entry '{t}' is not an integer issue number")
        by_status[e["status"]].append(e)

    for adr in sorted(accepted - seen):
        err(f"{adr} is accepted but has no entry in docs/implementation-status.yaml")

    if errors:
        for line in errors:
            print(f"FAIL {line}", file=sys.stderr)
        print(f"\n{len(errors)} finding(s).", file=sys.stderr)
        return 1

    counts = {s: len(by_status[s]) for s in VOCAB}
    lines: list[str] = []
    lines.append("<!-- Generated by scripts/generate-implementation-status.py from docs/implementation-status.yaml — do not edit by hand. -->")
    lines.append("")
    lines.append("# Implementation status")
    lines.append("")
    lines.append(
        "Where each accepted decision stands today — **decided** (written down), "
        "**implemented** (built in this repo and exercised in CI or the examples), "
        "and what only becomes **effective** once an adopter deploys it and promotes "
        "enforcement. Generated from `implementation-status.yaml`; CI fails if this "
        "report drifts from it, or if an accepted ADR is missing an entry."
    )
    lines.append("")
    lines.append("| Status | Count | Meaning |")
    lines.append("|---|---|---|")
    for s in VOCAB:
        lines.append(f"| {s} | {counts[s]} | {VOCAB_MEANING[s]} |")
    lines.append("")

    headings = {
        "implemented": "Implemented",
        "partial": "Partial",
        "decided": "Decided, not yet built",
        "proposed": "Proposed",
    }
    for s in VOCAB:
        group = sorted(by_status[s], key=lambda e: e["adr"])
        lines.append(f"## {headings[s]} ({counts[s]})")
        lines.append("")
        if not group:
            lines.append("_None._")
            lines.append("")
            continue
        for e in group:
            adr = e["adr"]
            num = adr.removeprefix("ADR-")
            meta = adrs[adr]
            label = f"[ADR {num}](decisions/{meta['file']}) — {meta['title']}"
            built = e.get("built", []) or []
            planned = e.get("planned", []) or []
            tracking = e.get("tracking", []) or []
            track = f" _(tracking: {', '.join('#' + str(t) for t in tracking)})_" if tracking else ""
            if s == "implemented":
                lines.append(f"- **{label}** — {join(built)}")
            else:
                lines.append(f"- **{label}**")
                if built:
                    lines.append(f"  - Built: {join(built)}")
                lines.append(f"  - Planned: {join(planned)}{track}")
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)}: {len(seen)} decisions "
          f"({', '.join(f'{counts[s]} {s}' for s in VOCAB if counts[s])}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
