#!/usr/bin/env python3
"""Generate the control map from the declared mappings.

This is the generator ADR 0021 §2 specifies: control mappings are declared
data (policies/ncua-glba/mappings.yaml); the bidirectional control map
(CONTROL-MAP.md) is a derived view, regenerated here and drift-checked in
CI so it cannot rot (AP-009). Coverage is explicit: controls with no
implementing policy render as declared gaps, never as silence (§3).

The generator also verifies every referenced policy file actually exists in
its module — a mapping that points at a deleted policy fails the build, which
is the whole point of deriving the map instead of hand-keeping it.

Usage: python scripts/generate-control-map.py
Exit 0 on success; 1 on a dangling policy reference or malformed mappings.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
MAPPINGS = REPO / "policies" / "ncua-glba" / "mappings.yaml"
OUTPUT = REPO / "policies" / "ncua-glba" / "CONTROL-MAP.md"

STATUS_LABEL = {
    "implemented": "✅ implemented",
    "manual": "📋 manual",
    "unimplemented": "⛔ unimplemented (declared gap)",
}


def main() -> int:
    data = yaml.safe_load(MAPPINGS.read_text(encoding="utf-8"))
    errors: list[str] = []

    lines = [
        "<!-- Generated by scripts/generate-control-map.py from mappings.yaml — do not edit by hand. -->",
        "<!-- Run `python scripts/generate-control-map.py` to regenerate. -->",
        "",
        "# Control map",
        "",
        "Derived from [`mappings.yaml`](./mappings.yaml) per [ADR 0021](../../docs/decisions/0021-ncua-glba-control-mapping-contract.md): the mappings are declared data, this map is a generated view, and CI fails on drift — so the map cannot rot (AP-009).",
        "",
        "> **Every mapping is a claim, pending compliance-partner acceptance.** Whether a policy satisfies a control to an examiner's standard is the partners' and the examiner's call, not a platform-team assertion. Coverage below is honest: controls with no implementing policy are explicit gaps, never silence.",
        "",
        "Frameworks referenced:",
        "",
    ]
    for key, fw in data["frameworks"].items():
        lines.append(f"- `{key}:` — {fw['name']}")

    counts = defaultdict(int)
    by_policy: dict[str, list[str]] = defaultdict(list)

    for family in data["control_families"]:
        lines += [
            "",
            f"## {family['name']} (`{family['id']}`)",
            "",
            f"Aggregation initiative (planned, issue #13): `{family['initiative']}`",
            "",
            "| Control | Title | Status | Implemented by | Evidence |",
            "|---|---|---|---|---|",
        ]
        for control in family["controls"]:
            counts[control["status"]] += 1
            ids = [f"`{control['id']}`"] + [f"`{a}`" for a in control.get("also", [])]
            impl_cells = []
            for impl in control.get("implemented_by", []):
                module = impl["module"]
                if "policy" in impl:
                    policy_path = REPO / "modules" / module / "policy" / f"{impl['policy']}.json"
                    if not policy_path.exists():
                        errors.append(f"{control['id']}: references missing policy modules/{module}/policy/{impl['policy']}.json")
                    impl_cells.append(f"[`{impl['policy']}`](../../modules/{module}/policy/{impl['policy']}.json)")
                    by_policy[f"modules/{module} → {impl['policy']}"].append(control["id"])
                else:
                    if not (REPO / "modules" / module).is_dir():
                        errors.append(f"{control['id']}: references missing module modules/{module}")
                    impl_cells.append(f"[`{module}`](../../modules/{module}/)")
                    by_policy[f"modules/{module} (module)"].append(control["id"])
            note = control.get("note")
            evidence = control.get("evidence", "—" if control["status"] != "unimplemented" else "n/a (gap)")
            lines.append(
                f"| {'<br>'.join(ids)} | {control['title']} | {STATUS_LABEL[control['status']]} | "
                f"{'<br>'.join(impl_cells) if impl_cells else '—'} | {evidence} |"
            )
            if note:
                lines.append(f"| | *{note}* | | | |")

    lines += [
        "",
        "## Coverage summary",
        "",
        "| Status | Count |",
        "|---|---|",
        f"| ✅ implemented | {counts['implemented']} |",
        f"| 📋 manual | {counts['manual']} |",
        f"| ⛔ unimplemented (declared gap) | {counts['unimplemented']} |",
        "",
        "## Reverse view — policy → controls",
        "",
        "| Implementing artifact | Provides evidence for |",
        "|---|---|",
    ]
    for artifact in sorted(by_policy):
        lines.append(f"| `{artifact}` | {', '.join(f'`{c}`' for c in by_policy[artifact])} |")

    lines += [
        "",
        "---",
        "",
        "*To add a family: declare it in `mappings.yaml` (controls, statuses, implementing policies, evidence sources), run the generator, commit both files. A mapping that references a policy file that does not exist fails CI.*",
        "",
    ]

    if errors:
        for e in errors:
            print(f"FAIL {e}", file=sys.stderr)
        return 1

    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    total = sum(counts.values())
    print(f"Wrote {OUTPUT.relative_to(REPO)}: {total} controls ({counts['implemented']} implemented, {counts['manual']} manual, {counts['unimplemented']} gaps)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
