#!/usr/bin/env python3
"""Generate each module's catalog-info.yaml from its manifest.yaml.

This is the converter ADR 0016 specifies: manifest.yaml is the source of
truth, catalog-info.yaml is a derived Backstage view produced by a pure
function. CI regenerates and fails on drift, so the catalog cannot rot
(AP-009). Never edit a catalog-info.yaml by hand.

The Domain and System entities are deliberately NOT generated per module;
they are the small static set in docs/catalog/catalog-info.yaml (ADR 0016
§3). This script emits only the per-module Component entities.

Output is hand-templated rather than yaml.dump()'d so the files are
byte-deterministic across Python versions.

Usage: python scripts/generate-catalog-info.py
Exit 0 on success; 1 on a malformed manifest.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent

# The repository this library lives in. An adopter who forks the repo updates
# this constant; it feeds the source-location annotation and links only.
REPO_URL = "https://github.com/justinbroadbent/vitruvius"

# Backstage lifecycles are coarser than module status (ADR 0016 §3); the
# exact status is preserved as a status-<value> tag.
LIFECYCLE = {
    "experimental": "experimental",
    "beta": "experimental",
    "stable": "production",
    "deprecated": "deprecated",
}

HEADER = """# Generated by scripts/generate-catalog-info.py from manifest.yaml — do not edit.
# The manifest is the source of truth; this file is a derived Backstage view (ADR 0016).
"""


def component_yaml(manifest: dict, area: str, name: str) -> str:
    meta, spec = manifest["metadata"], manifest["spec"]

    tags = [area, f"status-{meta['status']}"]
    tags += sorted(k for k, v in spec["cross_cutting"].items() if v)
    tags += [p for p in ("firmitas", "utilitas", "venustas") if p in spec["cites"]["principles"]]

    lines = [
        HEADER,
        "apiVersion: backstage.io/v1alpha1",
        "kind: Component",
        "metadata:",
        f"  name: {name}",
        # json.dumps quoting keeps free text (colons, quotes) valid YAML.
        f"  description: {json.dumps(meta['description'], ensure_ascii=False)}",
        "  tags:",
    ]
    lines += [f"    - {t}" for t in tags]
    lines += [
        "  annotations:",
        f"    backstage.io/source-location: url:{REPO_URL}/tree/main/modules/{area}/{name}/",
        "    backstage.io/techdocs-ref: dir:.",
    ]
    if spec["cites"]["decisions"]:
        lines.append(f"    vitruvius.io/cites-adrs: {','.join(spec['cites']['decisions'])}")
    if spec["cites"]["anti_patterns"]:
        lines.append(f"    vitruvius.io/cites-anti-patterns: {','.join(spec['cites']['anti_patterns'])}")
    if spec["dependencies"]["avm"]:
        avm = ",".join(f"{d['source']}@{d['version']}" for d in spec["dependencies"]["avm"])
        lines.append(f"    vitruvius.io/depends-on-avm: {avm}")
    lines += [
        "  links:",
        f"    - url: {REPO_URL}/blob/main/modules/{area}/{name}/manifest.yaml",
        "      title: Module manifest",
        "spec:",
        "  type: terraform-module",
        f"  lifecycle: {LIFECYCLE[meta['status']]}",
        f"  owner: group:{meta['owner']}",
        f"  system: {area}",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    manifests = sorted(REPO.glob("modules/*/*/manifest.yaml"))
    if not manifests:
        print("No manifests found.", file=sys.stderr)
        return 1

    for manifest_path in manifests:
        module_dir = manifest_path.parent
        area, name = module_dir.parent.name, module_dir.name
        try:
            manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
            rendered = component_yaml(manifest, area, name)
        except Exception as exc:
            print(f"FAIL {manifest_path.relative_to(REPO)}: {exc}", file=sys.stderr)
            return 1
        out = module_dir / "catalog-info.yaml"
        out.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(REPO)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
