#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generates docs/decisions/README.md from ADR YAML frontmatter.

.DESCRIPTION
    Reads frontmatter from each ADR in docs/decisions/, groups by category and
    status, and writes the index. CI runs this and fails if the result differs
    from the committed README.

    Run from the repo root:

        pwsh scripts/generate-adr-index.ps1

.NOTES
    Intentionally has zero external module dependencies — uses only built-in
    PowerShell and .NET. Avoids PSGallery/PyPI supply-chain exposure for a
    script that runs in CI.

    Compatible with PowerShell 5.1 (Windows) and PowerShell 7+ (cross-platform).

    The frontmatter parser is deliberately simple. It supports:
      - key: scalar-value
      - key: integer
      - key: [item, item, item]
      - key: []
    It does NOT support multi-line values, nested structures, or quoted strings
    with embedded colons. ADR frontmatter must stay within these constraints.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot  = Split-Path -Parent $PSScriptRoot
$adrDir    = Join-Path $repoRoot 'docs/decisions'
$indexFile = Join-Path $adrDir   'README.md'

function ConvertFrom-SimpleFrontmatter {
    param(
        [Parameter(Mandatory)]
        [string]$Text
    )

    if ($Text -notmatch "(?s)^---\r?\n(.*?)\r?\n---\r?\n") {
        return $null
    }
    $body = $Matches[1]

    $result = [ordered]@{}
    foreach ($line in ($body -split "\r?\n")) {
        if ($line -match '^([a-zA-Z0-9_]+):\s*(.*)$') {
            $key   = $Matches[1]
            $value = $Matches[2].Trim()

            if ($value -match '^\[\s*\]$') {
                $result[$key] = @()
            }
            elseif ($value -match '^\[(.+)\]$') {
                $items = $Matches[1] -split ',' | ForEach-Object { $_.Trim() }
                $result[$key] = @($items)
            }
            elseif ($value -match '^\d+$') {
                $result[$key] = [int]$value
            }
            else {
                $result[$key] = $value
            }
        }
    }

    return $result
}

function Get-Adrs {
    $adrs = @()
    # Filter via Where-Object rather than -Filter; PowerShell's -Filter on
    # non-Windows uses a different glob engine that doesn't honor the
    # bracket-class pattern. The regex is explicit and portable.
    Get-ChildItem -Path $adrDir -File | Where-Object { $_.Name -match '^[0-9]{4}-.*\.md$' } | Sort-Object Name | ForEach-Object {
        $text = Get-Content -Raw -LiteralPath $_.FullName
        $meta = ConvertFrom-SimpleFrontmatter -Text $text
        # Hard failures, not warnings: a silently-skipped ADR would vanish
        # from the generated index while CI stays green.
        if ($null -eq $meta) {
            throw "$($_.Name): missing or malformed YAML frontmatter"
        }
        foreach ($required in @('id', 'title', 'status', 'date', 'categories')) {
            if (-not $meta.Contains($required)) {
                throw "$($_.Name): frontmatter is missing required key '$required'"
            }
        }
        $prefix = [int]$_.Name.Substring(0, 4)
        if ([int]$meta['id'] -ne $prefix) {
            throw "$($_.Name): frontmatter id '$($meta['id'])' does not match filename prefix '$prefix'"
        }
        $meta['filename'] = $_.Name
        $adrs += , $meta
    }
    return , $adrs
}

function Format-AdrIndex {
    param([array]$Adrs)

    $lines = New-Object 'System.Collections.Generic.List[string]'
    $lines.Add('<!-- Generated by scripts/generate-adr-index.ps1 — do not edit by hand. -->')
    $lines.Add('<!-- Run `pwsh scripts/generate-adr-index.ps1` to regenerate. -->')
    $lines.Add('')
    $lines.Add('# Architecture Decision Records (ADRs)')
    $lines.Add('')
    $lines.Add('Index of ADRs in this repo, grouped by category. Each ADR is a single decision with its context, consequences, and citations. ADRs are kept flat and numbered sequentially; this index is the navigational view.')
    $lines.Add('')

    $lines.Add('## All ADRs (chronological)')
    $lines.Add('')
    $lines.Add('| ID | Title | Status | Categories | Date |')
    $lines.Add('|---|---|---|---|---|')
    foreach ($a in $Adrs) {
        $idStr = '{0:0000}' -f $a.id
        $cats  = @($a.categories) -join ', '
        $lines.Add("| [$idStr]($($a.filename)) | $($a.title) | $($a.status) | $cats | $($a.date) |")
    }
    $lines.Add('')

    # When superseded ADRs exceed ~20% of total, consider moving them to
    # docs/decisions/superseded/ and updating this script to walk subdirectories.
    # Until then, flat layout + this status grouping is the right convention.

    $lines.Add('## By category')
    $lines.Add('')
    $catMap = [ordered]@{}
    foreach ($a in $Adrs) {
        foreach ($c in @($a.categories)) {
            if (-not $catMap.Contains($c)) {
                $catMap[$c] = New-Object 'System.Collections.Generic.List[object]'
            }
            $catMap[$c].Add($a)
        }
    }
    foreach ($c in ($catMap.Keys | Sort-Object)) {
        $lines.Add("### $c")
        $lines.Add('')
        foreach ($a in $catMap[$c]) {
            $idStr = '{0:0000}' -f $a.id
            $lines.Add("- [$idStr]($($a.filename)) — $($a.title)")
        }
        $lines.Add('')
    }

    $lines.Add('## By status')
    $lines.Add('')
    $statusMap = [ordered]@{}
    foreach ($a in $Adrs) {
        if (-not $statusMap.Contains($a.status)) {
            $statusMap[$a.status] = New-Object 'System.Collections.Generic.List[object]'
        }
        $statusMap[$a.status].Add($a)
    }
    foreach ($s in ($statusMap.Keys | Sort-Object)) {
        $lines.Add("### $s ($($statusMap[$s].Count))")
        $lines.Add('')
        foreach ($a in $statusMap[$s]) {
            $idStr = '{0:0000}' -f $a.id
            $lines.Add("- [$idStr]($($a.filename)) — $($a.title)")
        }
        $lines.Add('')
    }

    # Join with LF (not CRLF) for consistency with the rest of the repo.
    return ($lines -join "`n")
}

$adrs = Get-Adrs
if ($adrs.Count -eq 0) {
    Write-Error 'No ADRs found.'
    exit 1
}

$rendered = Format-AdrIndex -Adrs $adrs

# Use System.IO to control encoding (UTF-8, no BOM) and line endings (LF).
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($indexFile, $rendered, $utf8NoBom)

$relPath = $indexFile.Substring($repoRoot.Length + 1) -replace '\\', '/'
Write-Host "Wrote $relPath with $($adrs.Count) ADRs"
